apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

images:
- name: jkvuacamila/provafinalfront-devops
  newTag: latest
- name: provafinalfront
  newName: jkvuacamila/provafinalfront-devops
  newTag: 206c5064ec87aa2c46d8ef929a300e1f62a0e2bc
- name: provafinalfront-devops
  newName: jkvuacamila/provafinalfront
  newTag: e4af0c0a900d9e60e572aaec9b36752e0e7855be
