apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

images:
- name: jkvuacamila/provafinalfront-devops
  newTag: latest
- name: provafinalfront
  newName: jkvuacamila/provafinalfront-devops
  newTag: 55e968c7d056c3cc1ffb0ea5dfb77f9a03966649
- name: provafinalfront-devops
  newName: jkvuacamila/provafinalfront
  newTag: e4af0c0a900d9e60e572aaec9b36752e0e7855be
