apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

images:
- name: jkvuacamila/provafinalfront-devops
  newTag: latest
- name: provafinalfront
  newName: jkvuacamila/provafinalfront-devops
  newTag: a94f125bfc69e39cb1fa68f36f51224e604f81a3
- name: provafinalfront-devops
  newName: jkvuacamila/provafinalfront
  newTag: e4af0c0a900d9e60e572aaec9b36752e0e7855be
