apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

images:
- name: jkvuacamila/provafinalfront-devops
  newTag: latest
- name: provafinalfront
  newName: jkvuacamila/provafinalfront-devops
  newTag: 3b6513b22f0c79b42aec5a9d1c47d7a3c67ab22b
- name: provafinalfront-devops
  newName: jkvuacamila/provafinalfront
  newTag: e4af0c0a900d9e60e572aaec9b36752e0e7855be
